{
  "hash": "fd6ef39d978f09d93cf130bae598dfa9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Verify the Claim: Poverty Change in Philadelphia\"\nauthor: \"Yuqi Zhang\"\ndate: 9/17/2026\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-summary: \"Show code\"\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Introduction\n\nThis analysis evaluates claims about changes in poverty in Philadelphia using ACS 5-year estimates. The article compares poverty conditions between the 2006–2010 and 2013–2017 ACS periods. Because the neighborhood boundaries used in the article are not published Census geographies, this analysis evaluates change at the census tract level.\n\n## Part 1 — Reconstruct\n\nThe analysis uses ACS 5-year estimates for Philadelphia census tracts. I use table B17001, *Poverty Status in the Past 12 Months by Sex by Age*. Variable `B17001_001` represents the total population for whom poverty status is determined, while `B17001_002` represents the population whose income in the past 12 months was below the poverty level.\n\nI use the 2010 ACS 5-year estimate to represent 2006–2010 and the 2017 ACS 5-year estimate to represent 2013–2017. These periods do not overlap. Because the article does not publish the exact census tracts used to construct its neighborhood estimates, I analyze individual census tracts rather than attempting to reproduce the article's neighborhood boundaries.\n\n\n\n### ACS data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#download 2010 data\npoverty_2010 <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    below_poverty = \"B17001_002\",\n    total = \"B17001_001\"\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2010,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#download 2017 data\npoverty_2017 <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    below_poverty = \"B17001_002\",\n    total = \"B17001_001\"\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2017,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_2010 <- poverty_2010 %>%\n  mutate(\n    poverty_rate = below_povertyE / totalE,\n    poverty_moe = moe_prop(\n      below_povertyE, totalE,\n      below_povertyM, totalM\n    )\n  )\n\npoverty_2017 <- poverty_2017 %>%\n  mutate(\n    poverty_rate = below_povertyE / totalE,\n    poverty_moe = moe_prop(\n      below_povertyE, totalE,\n      below_povertyM, totalM\n    )\n  )\n```\n:::\n\n## Part 2 — Test\n\nFor each census tract, I calculate the poverty rate and its margin of error. I then evaluate estimate reliability using the coefficient of variation (CV), compare poverty rates between the two ACS periods, and test whether the observed changes are statistically distinguishable from zero at the 90% confidence level.\n\n### Missing values\n\nSeven census tracts in 2006–2010 and eight census tracts in 2013–2017 have a total population of zero for whom poverty status is determined. Because a poverty rate cannot be calculated when the denominator is zero, these tracts are excluded from the rate and change analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_2010 <- poverty_2010 %>%\n  filter(totalE > 0)\n\npoverty_2017 <- poverty_2017 %>%\n  filter(totalE > 0)\n```\n:::\n\n\n### Estimate reliability\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_2010 <- poverty_2010 %>%\n  mutate(\n    cv = (poverty_moe / 1.645) / poverty_rate * 100,\n    reliability = case_when(\n      cv < 12 ~ \"Reliable\",\n      cv <= 40 ~ \"Somewhat reliable\",\n      TRUE ~ \"Unreliable\"\n    )\n  )\n\npoverty_2017 <- poverty_2017 %>%\n  mutate(\n    cv = (poverty_moe / 1.645) / poverty_rate * 100,\n    reliability = case_when(\n      cv < 12 ~ \"Reliable\",\n      cv <= 40 ~ \"Somewhat reliable\",\n      TRUE ~ \"Unreliable\"\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_2010 %>% count(reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability           n\n  <chr>             <int>\n1 Reliable             11\n2 Somewhat reliable   321\n3 Unreliable           45\n```\n\n\n:::\n\n```{.r .cell-code}\npoverty_2017 %>% count(reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability           n\n  <chr>             <int>\n1 Reliable             22\n2 Somewhat reliable   332\n3 Unreliable           22\n```\n\n\n:::\n:::\n\n\n### Change over time\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_change <- poverty_2010 %>%\n  select(\n    GEOID,\n    rate_2010 = poverty_rate,\n    moe_2010 = poverty_moe\n  ) %>%\n  inner_join(\n    poverty_2017 %>%\n      select(\n        GEOID,\n        NAME,\n        rate_2017 = poverty_rate,\n        moe_2017 = poverty_moe\n      ),\n    by = \"GEOID\"\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested <- poverty_change %>%\n  mutate(\n    change = rate_2017 - rate_2010,\n    se_2010 = moe_2010 / 1.645,\n    se_2017 = moe_2017 / 1.645,\n    se_diff = sqrt(se_2010^2 + se_2017^2),\n    moe_diff = se_diff * 1.645,\n    z = change / se_diff,\n    significant = abs(z) > 1.645\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested <- poverty_tested %>%\n  mutate(\n    rate_2010_pct = rate_2010 * 100,\n    rate_2017_pct = rate_2017 * 100,\n    change_pct = change * 100,\n    moe_diff_pct = moe_diff * 100,\n    tract = str_extract(NAME, \"Census Tract [^,]+\")\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested %>%\n  count(significant)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  significant     n\n  <lgl>       <int>\n1 FALSE         313\n2 TRUE           63\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested %>%\n  filter(significant) %>%\n  mutate(\n    direction = if_else(change > 0, \"Increase\", \"Decrease\")\n  ) %>%\n  count(direction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  direction     n\n  <chr>     <int>\n1 Decrease     27\n2 Increase     36\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested %>%\n  filter(significant) %>%\n  arrange(desc(abs(change_pct))) %>%\n  slice_head(n = 15) %>%\n  ggplot(aes(\n    x = reorder(tract, change_pct),\n    y = change_pct\n  )) +\n  geom_col(aes(fill = change > 0)) +\n  geom_errorbar(\n    aes(\n      ymin = change_pct - moe_diff_pct,\n      ymax = change_pct + moe_diff_pct\n    ),\n    width = 0.3\n  ) +\n  geom_hline(\n    yintercept = 0,\n    linetype = \"dashed\"\n  ) +\n  coord_flip() +\n  theme_minimal() +\n  guides(fill = \"none\") +\n  labs(\n    title = \"Largest statistically detectable changes in poverty rate\",\n    subtitle = \"Philadelphia census tracts, 2006–2010 to 2013–2017 ACS 5-year estimates\",\n    x = NULL,\n    y = \"Change in poverty rate (percentage points)\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment3_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n### Reliability of poverty estimates\n\n::: {.cell}\n\n```{.r .cell-code}\nreliability_table <- poverty_2017 %>%\n  filter(\n    !is.na(cv),\n    is.finite(cv)\n  ) %>%\n  mutate(\n    dot = case_when(\n      cv < 12 ~ \"🟢\",\n      cv <= 40 ~ \"🟡\",\n      TRUE ~ \"🔴\"\n    ),\n    tract = str_extract(NAME, \"Census Tract [^,]+\"),\n    poverty_rate_pct = poverty_rate * 100\n  ) %>%\n  arrange(desc(cv)) %>%\n  slice_head(n = 15) %>%\n  select(\n    dot,\n    tract,\n    poverty_rate_pct,\n    cv,\n    reliability\n  )\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreliability_table %>%\n  gt() %>%\n  fmt_number(\n    columns = poverty_rate_pct,\n    decimals = 1\n  ) %>%\n  fmt_number(\n    columns = cv,\n    decimals = 1\n  ) %>%\n  cols_label(\n    dot = \"\",\n    tract = \"Census tract\",\n    poverty_rate_pct = \"Poverty rate (%)\",\n    cv = \"CV (%)\",\n    reliability = \"Reliability\"\n  ) %>%\n  tab_header(\n    title = \"Census tracts with the least reliable poverty estimates\",\n    subtitle = \"Philadelphia, 2013–2017 ACS 5-year estimates\"\n  ) %>%\n  tab_source_note(\n    \"Reliability thresholds follow Jurjevich et al. (2018): CV < 12% reliable, 12–40% somewhat reliable, > 40% unreliable.\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kcezgvopog\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kcezgvopog table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kcezgvopog thead, #kcezgvopog tbody, #kcezgvopog tfoot, #kcezgvopog tr, #kcezgvopog td, #kcezgvopog th {\n  border-style: none;\n}\n\n#kcezgvopog p {\n  margin: 0;\n  padding: 0;\n}\n\n#kcezgvopog .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kcezgvopog .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kcezgvopog .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kcezgvopog .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kcezgvopog .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kcezgvopog .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kcezgvopog .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kcezgvopog .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kcezgvopog .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kcezgvopog .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kcezgvopog .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kcezgvopog .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kcezgvopog .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kcezgvopog .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kcezgvopog .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezgvopog .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kcezgvopog .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kcezgvopog .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kcezgvopog .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezgvopog .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kcezgvopog .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezgvopog .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kcezgvopog .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezgvopog .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezgvopog .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezgvopog .gt_left {\n  text-align: left;\n}\n\n#kcezgvopog .gt_center {\n  text-align: center;\n}\n\n#kcezgvopog .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kcezgvopog .gt_font_normal {\n  font-weight: normal;\n}\n\n#kcezgvopog .gt_font_bold {\n  font-weight: bold;\n}\n\n#kcezgvopog .gt_font_italic {\n  font-style: italic;\n}\n\n#kcezgvopog .gt_super {\n  font-size: 65%;\n}\n\n#kcezgvopog .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kcezgvopog .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kcezgvopog .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kcezgvopog .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kcezgvopog .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kcezgvopog .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kcezgvopog .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kcezgvopog .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kcezgvopog div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\" style>Census tracts with the least reliable poverty estimates</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Philadelphia, 2013–2017 ACS 5-year estimates</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dot\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"tract\">Census tract</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"poverty_rate_pct\">Poverty rate (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"cv\">CV (%)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"reliability\">Reliability</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9891</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">92.5</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">144.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9800</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">4.9</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">85.6</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 231</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">0.8</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">66.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 256</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">3.6</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">64.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9801</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">13.3</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">61.5</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 386</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">59.3</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 9802</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">11.5</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">51.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 340</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">9.7</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">47.9</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 347.02</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">47.1</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 10.02</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">6.4</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">46.7</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 220</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">1.3</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">45.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 363.03</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">5.7</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">44.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 29</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">17.6</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">43.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 341</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">9.8</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">42.4</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n    <tr><td headers=\"dot\" class=\"gt_row gt_left\">🔴</td>\n<td headers=\"tract\" class=\"gt_row gt_left\">Census Tract 365.01</td>\n<td headers=\"poverty_rate_pct\" class=\"gt_row gt_right\">12.6</td>\n<td headers=\"cv\" class=\"gt_row gt_right\">42.2</td>\n<td headers=\"reliability\" class=\"gt_row gt_left\">Unreliable</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"5\">Reliability thresholds follow Jurjevich et al. (2018): CV &lt; 12% reliable, 12–40% somewhat reliable, &gt; 40% unreliable.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested %>%\n  ggplot(aes(\n    x = rate_2010_pct,\n    y = rate_2017_pct\n  )) +\n  geom_point(alpha = 0.6) +\n  geom_abline(\n    slope = 1,\n    intercept = 0,\n    linetype = \"dashed\"\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Poverty rates across Philadelphia census tracts\",\n    subtitle = \"2006–2010 compared with 2013–2017 ACS 5-year estimates\",\n    x = \"Poverty rate, 2006–2010 (%)\",\n    y = \"Poverty rate, 2013–2017 (%)\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment3_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\nThe scatterplot shows substantial variation across census tracts, but many points remain relatively close to the diagonal reference line, indicating limited change between the two periods. Several apparent large changes are present, but the significance test shows that most tract-level differences are not statistically distinguishable from zero.\n\n### Summary of results\n\n::: {.cell}\n\n```{.r .cell-code}\npoverty_tested %>%\n  summarize(\n    total_tracts = n(),\n    significant_change = sum(significant),\n    not_significant = sum(!significant),\n    significant_increase = sum(significant & change > 0),\n    significant_decrease = sum(significant & change < 0)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  total_tracts significant_change not_significant significant_increase\n         <int>              <int>           <int>                <int>\n1          376                 63             313                   36\n# ℹ 1 more variable: significant_decrease <int>\n```\n\n\n:::\n:::\n\nOf the 376 census tracts included in the comparison, 63 showed a statistically detectable change in poverty rate at the 90% confidence level, while 313 did not. Among the tracts with statistically significant change, 36 experienced an increase in poverty rate and 27 experienced a decrease. This means that most apparent tract-level changes between the two ACS periods are not statistically distinguishable from sampling uncertainty.\n\nThe reliability analysis also shows that most tract estimates fall in the “Somewhat reliable” category. The number of reliable estimates increased from 11 in 2006–2010 to 22 in 2013–2017, while the number of unreliable estimates decreased from 45 to 22. These results show why margins of error and estimate reliability are important when interpreting apparent neighborhood-level change.\n\n## Part 3 — Adjudicate\n\n### Supported\n\nThe article's broader claim that poverty increased substantially in some parts of Philadelphia is supported by the tract-level analysis. Of the 376 census tracts included in the comparison, 63 experienced a statistically detectable change in poverty rate at the 90% confidence level. Among these, 36 tracts experienced a significant increase and 27 experienced a significant decrease. This confirms that meaningful increases in poverty occurred in some parts of the city, although they were not universal.\n\n### Not supported\n\nThe data do not support treating most apparent changes across Philadelphia as clear evidence of real change. Of the 376 tracts analyzed, 313 did not show a statistically detectable change. In addition, most poverty-rate estimates were classified as only “Somewhat reliable.” Therefore, differences between the two ACS periods should not automatically be interpreted as meaningful change without considering margins of error.\n\n### Cannot be determined\n\nSeveral of the article's most specific claims cannot be reproduced with this analysis. The article reports that Eastwick had the largest poverty-rate increase, that Holmesburg's poverty rate rose from 2% to 19%, and that Fairhill had a 61% poverty rate. However, the article does not publish the census tracts used to construct its neighborhood boundaries, so these neighborhood-level estimates cannot be directly replicated using tract-level data.\n\nThe claim that poverty increased specifically among white residents also cannot be evaluated with this analysis because the variables used here measure overall poverty rather than poverty by race. Claims about changes in neighborhood income inequality also require additional income variables that are not included in this analysis.\n\n## Part 4 — Rewrite\n\nPhiladelphia's 2013–2017 ACS estimates suggest that poverty increased in some parts of the city, but the pattern is less uniform than raw neighborhood comparisons imply. Among 376 census tracts analyzed, 63 showed a statistically detectable change in poverty rate compared with 2006–2010: 36 increased and 27 decreased. The remaining 313 tracts did not show a change that could be distinguished from sampling uncertainty at the 90% confidence level. Most tract-level estimates were also only somewhat reliable based on their coefficients of variation. Because the original article does not publish the census tracts used to define neighborhoods such as Eastwick, Fairhill, and Holmesburg, its specific neighborhood-level claims cannot be directly reproduced here. The ACS indicates real pockets of worsening poverty, but many apparent changes should be interpreted cautiously.\n",
    "supporting": [
      "assignment3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}