{
  "hash": "b842b3663f063e532d016132afc13e22",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Yuqi Zhang\"\ndate: 2026-09-08\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, In this assignment, I examine median gross rent across\ncounties and county-equivalents in Virginia. I compare their margins of error to\nidentify which communities are measured more reliably and which have greater\nuncertainty.\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"VA\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25064_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 133   5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                        variable   estimate   moe\n  <chr> <chr>                       <chr>         <dbl> <dbl>\n1 51001 Accomack County, Virginia   B25064_001      973    59\n2 51003 Albemarle County, Virginia  B25064_001     1623    38\n3 51005 Alleghany County, Virginia  B25064_001      774   109\n4 51007 Amelia County, Virginia     B25064_001      972   126\n5 51009 Amherst County, Virginia    B25064_001      842    38\n6 51011 Appomattox County, Virginia B25064_001      883    73\n```\n\n\n:::\n:::\n\n\n**The dataset contains 133 rows, representing Virginia’s 95 counties and 38 independent cities, which are treated as county-equivalent geographies in the ACS.**\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                            estimate   moe moe_pct\n   <chr>                              <dbl> <dbl>   <dbl>\n 1 Surry County, Virginia               858   257    30.0\n 2 Greene County, Virginia             1502   409    27.2\n 3 Covington city, Virginia             822   220    26.8\n 4 Powhatan County, Virginia           1107   293    26.5\n 5 King William County, Virginia       1246   296    23.8\n 6 Bath County, Virginia                825   180    21.8\n 7 Northumberland County, Virginia     1053   197    18.7\n 8 Lexington city, Virginia             985   181    18.4\n 9 Madison County, Virginia            1048   189    18.0\n10 Rappahannock County, Virginia       1384   241    17.4\n```\n\n\n:::\n:::\n\n\n**Surry County has the largest margin of error relative to its estimate. Its margin of error is approximately 30.0% of the estimated median gross rent, making it the least reliably measured geography in this dataset.**\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    49\n2 Low confidence     27\n3 Moderate           57\n```\n\n\n:::\n:::\n\n\n**There are 49 county-equivalent geographies in the high-confidence category, 57 in the moderate-confidence category, and 27 in the low-confidence category.**\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row. This requires a wide-format ACS pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                        myvarE myvarM   popE  popM\n  <chr> <chr>                        <dbl>  <dbl>  <dbl> <dbl>\n1 51001 Accomack County, Virginia      973     59  33326    NA\n2 51003 Albemarle County, Virginia    1623     38 113683    NA\n3 51005 Alleghany County, Virginia     774    109  14962    NA\n4 51007 Amelia County, Virginia        972    126  13342    NA\n5 51009 Amherst County, Virginia       842     38  31385    NA\n6 51011 Appomattox County, Virginia    883     73  16424    NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         49        134521.\n2 Low confidence          13         12508.\n3 Moderate                71         26808.\n```\n\n\n:::\n:::\n\n\n**High-confidence counties have an average population of approximately 134,521, while low-confidence counties have an average population of only 12,508. Moderate-confidence counties fall in between, with an average population of about 26,808. This shows a clear pattern: counties with smaller populations tend to have larger margins of error relative to their estimates.**\n\n---\n\n## What this means for policy\n\nThe ACS data show that we know the least about some smaller communities in Virginia when measuring median gross rent. Surry County has the largest relative margin of error at 30.0%, followed by Greene County at 27.2%, Covington city at 26.8%, and Powhatan County at 26.5%. These large margins of error mean that their rent estimates are less precise than estimates for communities with smaller margins of error.\n\nThis pattern is related to how the ACS works. The ACS is based on a sample rather than a complete count of every household. Smaller communities generally have smaller samples, which creates more uncertainty in their estimates. My results show this pattern clearly. High-confidence counties have an average population of about 134,521, while low-confidence counties have an average population of only 12,508. Moderate-confidence counties fall in between, with an average population of about 26,808.\n\nThis uncertainty could cause problems if a state agency used median gross rent to allocate affordable housing funding or rental assistance while treating every estimate as equally certain. Smaller communities with large margins of error would be especially vulnerable. For example, if their estimated rent is lower than the actual rent, they might receive less housing assistance than they actually need. If it is higher than the actual rent, funding might be directed there instead of to communities with greater needs. Therefore, agencies should consider both ACS estimates and their margins of error when making funding decisions.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}